offset:
  head_pan: 0
  head_tilt: 0
  l_ank_pitch: -0.03835
  l_ank_roll: 0.0
  l_el: 0
  l_hip_pitch: 0
  l_hip_roll: -0.01534
  l_hip_yaw: 0
  l_knee: 0
  l_sho_pitch: 0
  l_sho_roll: 0
  r_ank_pitch: 0.03068
  r_ank_roll: 0
  r_el: 0
  r_hip_pitch: -0.01534
  r_hip_roll: 0
  r_hip_yaw: 0
  r_knee: 0
  r_sho_pitch: 0
  r_sho_roll: 0
